# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('articles', '0002_remove_projectpage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('author_list', wagtail.wagtailcore.fields.StreamField([('author', wagtail.wagtailcore.blocks.StructBlock([(b'name', wagtail.wagtailcore.blocks.CharBlock()), (b'institution', wagtail.wagtailcore.blocks.CharBlock(null=True, required=False))]))])),
                ('year', models.CharField(max_length=4, null=True)),
                ('abstract', wagtail.wagtailcore.fields.RichTextField(null=True)),
                ('pub_link', wagtail.wagtailcore.fields.StreamField([('link', wagtail.wagtailcore.blocks.StructBlock([(b'url', wagtail.wagtailcore.blocks.URLBlock(null=True, required=False)), (b'pdf', wagtail.wagtaildocs.blocks.DocumentChooserBlock(null=True, required=False))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
