# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_publicationpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='abstract',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='author_list',
            field=wagtail.wagtailcore.fields.StreamField([('author', wagtail.wagtailcore.blocks.StructBlock([(b'name', wagtail.wagtailcore.blocks.CharBlock()), (b'institution', wagtail.wagtailcore.blocks.CharBlock(null=True, required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='pub_link',
            field=wagtail.wagtailcore.fields.StreamField([('link', wagtail.wagtailcore.blocks.StructBlock([(b'url', wagtail.wagtailcore.blocks.URLBlock(null=True, required=False)), (b'pdf', wagtail.wagtaildocs.blocks.DocumentChooserBlock(null=True, required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
