# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('articles', '0004_auto_20171228_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationpage',
            name='pub_link',
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
