# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20171229_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationpage',
            old_name='year',
            new_name='date',
        ),
    ]
