# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20171229_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='journal',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
