# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('projects', '0003_auto_20171218_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
