# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
