# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20171219_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personpage',
            name='name',
        ),
    ]
