# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171219_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='brief_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
