# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0006_homepagefunder'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='secondary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
