# Generated by Django 2.1.4 on 2019-11-03 13:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freestylepage',
            name='body',
            field=wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('images', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('blurb', wagtail.core.blocks.RichTextBlock(required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(help_text='Ignored if page is set', required=False))])))])), ('image_link_columns', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('image_links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('url', wagtail.core.blocks.URLBlock(required=False))]))), ('style', wagtail.core.blocks.ChoiceBlock(choices=[('dark', 'Dark'), ('light', 'Light')]))])), ('text_columns', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('text', wagtail.core.blocks.RichTextBlock(required=False))]))), ('style', wagtail.core.blocks.ChoiceBlock(choices=[('dark', 'Dark'), ('light', 'Light')]))])), ('recent_publications', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('style', wagtail.core.blocks.ChoiceBlock(choices=[('dark', 'Dark'), ('light', 'Light')]))])), ('current_projects', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('style', wagtail.core.blocks.ChoiceBlock(choices=[('dark', 'Dark'), ('light', 'Light')]))]))]),
        ),
    ]
